default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  primary: &primary_production
    <<: *default
      adapter: postgresql
      encoding: unicode
      # Render では DATABASE_URL が自動的に設定されます
      url: <%= ENV['DATABASE_URL'] %>
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
      database: oursite
      username: oursite_user_
      password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
      url: <%= ENV['DATABASE_URL'] %>
  cache:
      <<: *primary_production
  queue:
      <<: *primary_production
    # Action Cable 用設定（本番のみ）
  cable:
    production:
      adapter: postgresql
      url: <%= ENV['DATABASE_URL'] %>

